### ISSUE TITLE
Request API to set/get command timeout timer

### ISSUE THREAD

**Issue by FolandZhang** [cranechu/pynvme#26]
Usually, we have some commands need specify command max execution time(ie, NVM_Fomat command maybe cost about 40s). So request this API to set command TO timer to meet requirement.

I also need get command TO timer API to get current command TO timer.

Thanks a lot!

**Comment by cranechu** [comment]
Controller.timeout: user can get and set this value in milli-seconds. 

Example:
nvme0.timeout=10
assert nvme0.timeout == 10
