### ISSUE TITLE
Request IOworker API supports different data pattern specify by user

### ISSUE THREAD

**Issue by FolandZhang** [cranechu/pynvme#28]
Generally, I expected ioworker API could support different data pattern, which allowed set by user.

Below data patterns suggest to support but not limit to:
1. All zeros;
2. All ones;
3. User defined value; (ie, set 0x5A, buffer pattern is repeating 5A);
4. Random pattern;
5. Different entropy (%);
and so on.

Thanks a lot!

**Comment by cranechu** [comment]
We implemented all these patterns in v1.3. 
Scripts can identify ptype and pvalue for Buffer and ioworker. 

        pvalue (int): data pattern value. Default: 0
            Different pattern type has different value definition:
            0: 1-bit pattern: 0 for all-zero data, 1 for all-one data
            32: 32-bit pattern: 32-bit value of the pattern 
            0xbeef: random data: random data compression percentage rate
            else: not supported
